---
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: install epel-release
  yum:
    name: epel-release
    state: latest


- name: Reboot
  reboot:
    reboot_timeout: 180
    pre_reboot_delay: 10
    post_reboot_delay: 20
  
