---
# tasks file for kuber_kubeadm_let_ctl

# - name: add sd kubernetes.repo
#   yum_repository:
#     name: kubernetes
#     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
#     enabled: yes
#     gpgcheck: yes
#     repo_gpgcheck: yes
#     gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
#     exclude:
#       - kubelet
#       - kubeadm
#       - kubectl
#     description: kubernetes
    

- name: disable selinux
  selinux:
    state: disabled


- name: ensure selinux is set to enforcing module
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX=disabled$'
    line: SELINUX=permissive

- name: Reboot
  reboot:
    reboot_timeout: 180
    pre_reboot_delay: 10
    post_reboot_delay: 20

- name: install kubeadm kubelet and kubectl rpm package
  shell: yum install -y 4d300a7655f56307d35f127d99dc192b6aa4997f322234e754f16aaa60fd8906-cri-tools-1.23.0-0.x86_64.rpm \
                        db7cb5cb0b3f6875f54d10f02e625573988e3e91fd4fc5eef0b1876bb18604ad-kubernetes-cni-0.8.7-0.x86_64.rpm\
                        d39aa6eb38a6a8326b7e88c622107327dfd02ac8aaae32eceb856643a2ad9981-kubelet-1.23.5-0.x86_64.rpm\
                        ab0e12925be5251baf5dd3b31493663d46e4a7b458c7a5b6b717f4ae87a81bd4-kubeadm-1.23.5-0.x86_64.rpm\
                        96b208380314a19ded917eaf125ed748f5e2b28a3cc8707a10a76a9f5b61c0df-kubectl-1.23.5-0.x86_64.rpm\
                        --disableexcludes=kubernetes

- name: add shekan for kubernetes
  shell: |
    cat <<EOF | sudo tee /etc/resolv.conf
    # Generated by NetworkManager
    nameserver 178.22.122.100
    nameserver 185.51.200.2
    nameserver 8.8.8.8
    EOF

# - name: install kubeadm, kubectl and kubelet 
#   command: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

- name: check install kubeadm, kubectl and kubelet
  package_facts:
    manager: "auto"

- name: kubeadm, kubectl and kubelet not found
  debug:
    msg: kubeadm, kubectl and kubelet not found
    var: ansible_facts.packages
  when: ('kubeadm' not in ansible_facts.packages) and ('kubectl' not in ansible_facts.packages) and ('kubelet' not in ansible_facts.packages)



- name: restart kubelet
  service:
    name: kubelet
    state: started
    enabled: yes
  when: ('kubeadm' in ansible_facts.packages) and ('kubectl' in ansible_facts.packages) and ('kubelet' in ansible_facts.packages)
